name: Terramate Terraform AWS

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Terramate install
        run: go install github.com/terramate-io/terramate/cmd/...@latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terramate Generate
        working-directory: S3
        run: terramate generate

      - name: Development
        working-directory: S3
        run: |
          terraform init -lock=false
          terraform apply -auto-approve -lock=false
          terraform destroy -auto-approve -lock=false
